### ISSUE TITLE
Make the app wasm compatible

### ISSUE THREAD

**Issue by TheRustyPickle** [TheRustyPickle/Talon#55]
Attempt to make the app wasm compatible to serve in the web

**Comment by TheRustyPickle** [comment]
│   ├── grammers-mtsender v0.5.0
│   │   ├── bytes v1.5.0
│   │   ├── futures-util v0.3.30 (*)
│   │   ├── grammers-mtproto v0.5.0 (*)
│   │   ├── grammers-tl-types v0.5.1 (*)
│   │   ├── log v0.4.20
│   │   └── tokio v1.36.0
│   │       ├── bytes v1.5.0
│   │       ├── libc v0.2.153
│   │       ├── mio v0.8.10
│   │       │   └── libc v0.2.153


mio is not wasm compatible! Likely won't be able to bypass it.

**Comment by nguyenvuonghlnb** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
tedt10e, @willjleong, @tomasovic, @tocoteron, @brightclark, @yanganto, @Un4G173N, @g-r-a-n-t, @juniuszhou, @abel-byte, @LXJ2, @dav8t, @hustxiaoc, @daweth, @1701175145, @DaviRain-Su, @3b40eb98, @rahulnm, @masami87, @Dmdv, @Shawndslee, @Glow-in-the-dark, @Darth123658, @ZGQ-inc, @defispartan, @rofuun, @haua998, @Lz1y, @Dougie008, @TalkWIthKeyboard, @massun-onibakuchi, @jakerumbles, @hzqd, @longcpp, @alikonuk1, @steffenix, @stan-dot, @weipin, @19-xiaogao, @fanyang1988, @xiaosongfu, @dimlev, @Folyd, @mshrieve, @deadblackclover, @mdtanrikulu, @NukeManDan, @zeroXbrock, @3ddi, @chenjunwen186p0p3yee, @astrolemonade, @SergioArrighi, @archi-cszcli, @daiwanwei, @pedrommaiaa, @randhindi, @yihau, @andreisilviudragnea, @idkwim, @Godaiandi, @fuyutarow, @limotree, @intdance, @ccamateur, @coopbri, @macrocan, @yaroslavyaroslav, @DennisDv24, @nkysg, @iamazy, @b00f, @ZhiXiao-Lin, @zkmsg, @HAOYUatHZ, @lowlowcoder, @thasarito, @MRGRAVITY817, @caoanlong, @franssl, @ivanceras, @dalaorock, @ccmlm, @marko-lazic, @asadkovich, @Apoll95, @rameight, @sorawit, @misoobu, @MoodyBoi, @eratzlaff, @saki-osive, @DukeCaesar, @sashaaldrick, @tacoda, @greyireland, @frost-scorpio, @chirag-bgh, @bredamatt, @marmelo-cotoneum

**Comment by otodak** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
wiznard, @xeno097, @JBLarson, @cyjrun, @NiBlack114, @PwnSecc, @shanechen0916, @eartht0sarah, @gzb4219, @librity, @shreyasrk, @NaelShichida, @gamerey43, @Vicksyn, @pratamawijaya, @Mr-ONADASKY, @nayeem-17, @astrolemonade, @fcarli3, @vgjm, @ohenepee, @kaustav202, @udittyagi, @nikhilkumar5294, @chauvansang, @darkmatter11235, @MrJ89Carrazco, @imdongchen, @rapturev, @GUESSZERO4, @lifeifeixz, @lindsaytennie, @kdeepak99, @lucassantos94, @bharath-b06, @yizhilee, @wiready, @frankiefab100, @seanyu-git, @cenzwong, @bimap98, @ltchr, @grmpyninja, @llss6887, @9M6, @LeoCp, @Phoenixfan, @cycloss, @b1xt, @adotsloanwigust, @Ocelani, @ropital, @webgurucan, @Sunchao1996, @Bazinga09, @omerkhawaja, @Monem-Shahriar, @Spyder15, @karolgro, @prairitm, @jaeyongjaykim, @mexanix, @jkyochen, @Mrs-Shadows, @slai-fi, @xlaoy, @M-abobakr, @xiaozhiliaoo, @averias, @liuxuleigitpub, @prite36, @DionysusBenstein, @vittalkolla, @Zeb-blockchain, @Laili2, @dfxshxr, @qdmudong, @bmorelax, @vincent0426, @Ay-355, @jogunfuwa, @BhoopathiSaisagar, @arvryna, @diivi, @kwabenasapong, @LeoMoonStar, @GaleevDinar, @kristsokoli, @aksinha334, @iBerezkin, @banshee0716, @suyanlong, @fruizrob, @lhp3851, @chhk-dev, @123mpozzi, @huazhuangnan, @doc22940, @zhouzhuojie

**Comment by taylorcammack** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
zerosnacks, @lambda-0x, @llifezou, @vernonjohnson, @lightning-li, @micrub, @sebastiantf, @somerb, @kss-fluency, @whilei, @ZGQ-inc, @enif-lee, @earthflower, @WilfredTA, @Just4Ease, @haua998, @kootsZhin, @valeryz, @felixangell, @IvonaldoAmaral, @orangemio, @vbrvk, @execnow, @marko-lazic, @moreal, @brandawsd, @kimpers, @nuts-rice, @ZiNai, @sbusso, @pistomat, @dackerer, @garious, @hustxiaoc, @r-tom90, @kriptoibo, @dineshpinto, @saman-pasha, @dimlev, @TomaszWaszczyk, @trmaphi, @guijunchen, @Dmdv, @Jawy77, @qymlyl, @denismaxim0v, @0xbillw, @longcpp, @2Higara, @gabrielfalcaop4r4no1ak, @0xethsign, @sgc109, @puzzithinker, @goncaloMagalhaes, @zzir, @zqhxuyuan, @hyperleex, @BoundlessCarrot, @cherry-yl-sh, @Archisman-Mridha, @X4, @seyedhanaee, @p0p3yee, @jtriley-eth, @diazMelgarejo, @onlymaresia, @dcbuild3r, @Animismo, @jonahcui, @rhizome01, @joyqvq, @cd1m0, @TalkWIthKeyboard, @mmacedoeu, @zhangzhongzhong, @edmand46, @pinardZ, @tmpfs, @ImpossibleReality, @TheRustyPickle, @nellyisanon, @tommy-ca, @asadkovich, @zachperez, @alfellati, @willjleong, @Shawndslee, @marmelo-cotoneum, @hineso11, @wstreet, @sorpaas, @ackintosh, @mia-stein, @HegelXu, @HAOYUatHZ, @mcass19, @fwx5618177, @darrylyeo, @DieracDelta
